export { schools };

const schools = [
    "Anima Christi Center for Learning and Human Development",
    "APEC",
    "Bay View Academy",
    "Christ Baptist Academy",
    "Christ the King School of Muntinlupa",
    "Christ the Living Intercessor Christian School",
    "Colegio de Muntinlupa",
    "Colegio de Nuestra Señora de Guadalupe",
    "Cupang Senior High School",
    "De La Salle Zobel School",
    "Divine Mercy School",
    "Emmanuel John Institute of Science And Technology, Inc",
    "Far Eastern University Alabang",
    "Facilities Management College",
    "Holy Queen of La Salette School",
    "Infant Jesus Montessori School of Muntinlupa - Parkhomes",
    "Kennedy International School of Business and Languages",
    "Lakewood School of Alabang",
    "Le Sainte School",
    "Liceo de Alabang, Inc",
    "Liceo de Piccolo Santo",
    "Living Light Academy",
    "Lombosco Academy Foundation, Inc",
    "Lyceum of Alabang INC",
    "Maria Ferarri School",
    "Maranatha Christian Academy - Bayanan",
    "Mary Cause of our Joy Catholic School",
    "Mary, Mother of God Parochial School",
    "MBC-Sinai School",
    "Miraculous Medal School",
    "MIT International School",
    "Muntinlupa Business High School",
    "Muntinlupa Cosmopolitan School",
    "Muntinlupa Institute of Technology (MIT",
    "Muntinlupa National High School",
    "Muntinlupa Science High School",
    "Our Lady of The Abandoned Catholic School",
    "Our Lady of the Lake School",
    "Pamantasan ng Lungsod ng Muntinlupa (PLMun",
    "PAREF Ridgefield School",
    "PAREF Rosemont School",
    "PAREF Southridge School",
    "Pedro E. Diaz High School",
    "Ridgeview Academy",
    "Sacred Heart Institute",
    "Santo Niño School of Muntinlupa",
    "Servite School, Inc",
    "Soldier's Hills Elementary School",
    "South Crest School",
    "Southernside Montessori School",
    "Spring Christian School",
    "STI College (Alabang Branch",
    "Sto. Domingo Pascual Academy, Inc",
    "Sunshine Christian School of Muntinlupa",
    "Theresiana de Montealegre Dame School",
    "The Birthright School of Muntinlupa",
    "Tunasan National High School",
    "Outside of Muntinlupa",
]